routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',  [HomeController::class, 'home'])->name('home');


Route::resource('categories', CategoryController::class);

Auth::routes();

Route::get('logout', [HomeController::class, 'logout']) ;

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class) ;
    Route::resource('users', UserController::class) ;
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    //

    public function index(Request $request)
    {
        $users = User::orderBy('id', 'desc')->paginate() ;

        return view('users.index', compact('users'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        $roles = Role::pluck('name', 'name')->all();

        return view('users.create', compact('roles')) ;
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);

        $input = $request->all() ;
        $input['password'] = Hash::make($input['password']) ;

        $user = User::create($input) ;
        $user->assignRole($request->input('roles')) ;

        return redirect()->route('users.index')->with('success', 'Utilisateur enregistré avec succès') ;
    }

    public function show($id)
    {
        $user = User::find($id) ;

        return view('users.show', compact('user')) ;
    }
}

resources/views/users/create.blade.php
@extends('layouts.layout')

@section('title')
    Enregistrer un nouvel utilisateur
@endsection

@section('body')

    <div class="container m-5">
        <div class="row">
            <div class="col-12">
                {!! Form::open(array('route' => 'users.store', 'method' => 'POST', 'class' => 'contact-form row', 'id' => 'main-contact-form')) !!}
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Nom Complet</strong>
                            {!! Form::text('name', null, ['placeholder' => 'Nom utilisateur', 'class' => 'form-control mb-2']) !!}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Email</strong>
                            {!! Form::email('email', null, ['placeholder' => 'Email', 'class' => 'form-control mb-2']) !!}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Mot de passe</strong>
                            {!! Form::password('password', null, ['placeholder' => 'Mot de passe', 'class' => 'form-control mb-2']) !!}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Confirmer de passe</strong>
                            {!! Form::password('confirm-password', null, ['placeholder' => 'Confirmer votre mot de passe', 'class' => 'form-control mb-2']) !!}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Rôles</strong>
                            {!! Form::select('roles[]', $roles, [], ['class' => 'form-control', 'multiple']) !!}
                        </div>
                    </div>
                    <div class="col-12">
                        {!! Form::submit('Enregistrer', ['class' => 'btn btn-block btn-primary']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.layout')

@section('title')
    Utilisateurs
@endsection

@section('body')

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="pull-left">
                    <h2>Gestion des utilisateurs</h2>
                </div>
                <div class="pull-right">
                    <a href="{{ route('users.create') }}" class="btn btn-outline-warning">Enregistrer un nouvel utilisateur</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">

                @if ($message = Session::get('success'))
                    <p>{{ $message }}</p>
                @endif

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>N°</th>
                            <th width="280px">Nom complet</th>
                            <th>Email</th>
                            <th>Rôles</th>
                            <th colspan="3" width="px">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @if (intval(count($user->getRoleNames())) != 0)
                                        @foreach ($user->getRoleNames() as $role)
                                            <label for="" class="badge badge-success">
                                                {{ $role }}
                                            </label>
                                        @endforeach
                                    @else
                                        <label for="" class="badge badge-secondary">
                                            Pas de rôle
                                        </label>
                                    @endif
                                </td>
                                <td>
                                    <a class="btn btn-info" href="{{ route('users.show', $user->id) }}">
                                        <span class="fa fa-eye"></span>
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-info" href="{{ route('users.edit', $user->id) }}">
                                        <span class="fa fa-edit"></span>
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-info" href="#">
                                        <span class="fa fa-trash"></span>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        {!! $users->render() !!}
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.layout')

@section('title')
    {{ $user->name }}
@endsection

@section('body')
    <div class="container m-5">
        <div class="row">
            <div class="col-12">
                <div class="form">
                    <strong>Nom complet : </strong>
                    {{ $user->name }}
                </div>
            </div>
            <div class="col-12">
                <div class="form">
                    <strong>Email : </strong>
                    {{ $user->email }}
                </div>
            </div>
            <div class="col-12">
                <div class="form">
                    <strong>Rôles :</strong>
                    @if (!empty($user->getRoleNames()))
                        @foreach ($user->getRoleNames() as $role)
                            <label for="" class="badge badge-success">
                                {{ $role }}
                            </label>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection('body')